export const SOCKET_EVENTS = {
    PING: "ping",
    PONG: "pong",
    SEND_MESSAGE: "send-message",
    NEW_MESSAGE: "receive-message",
    UPDATE_UNREAD_COUNT: "update-unread-count",
    MARK_READ: "mark-as-read",
    MESSAGE_READ: "message-read",
    PRIVATE_MESSAGE: "private-message",
    GET_MESSAGES: "get-messages",
    MESSAGE_HISTORY: "message-history",
    TYPING: "typing",
    STOP_TYPING: "stop-typing",
    USER_ONLINE: "user-online",
    USER_OFFLINE: "user-offline",
    CONVERSATION_UPDATE : "conversation-update",
};